FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY FrontEnd/FrontEnd.csproj FrontEnd/
RUN dotnet restore FrontEnd/FrontEnd.csproj

COPY FrontEnd/ FrontEnd/

WORKDIR /src/FrontEnd
RUN dotnet publish FrontEnd.csproj -c Release -o /app/publish --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

ENTRYPOINT ["dotnet", "FrontEnd.dll"]