FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY BackEnd/BackEnd.csproj BackEnd/
RUN dotnet restore BackEnd/BackEnd.csproj

COPY BackEnd/ BackEnd/

RUN rm -rf BackEnd/bin BackEnd/obj

RUN dotnet restore BackEnd/BackEnd.csproj

WORKDIR /src/BackEnd

RUN dotnet publish BackEnd.csproj -c Release -o /app/publish --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8081

EXPOSE 8081

ENTRYPOINT ["dotnet", "BackEnd.dll"]